### ISSUE TITLE
HandleColor doesn't change color of background

### ISSUE THREAD

**Issue by Liliana99** [GroovinChip/modal_drawer_handle#1]
Hi,

I've install the plugin , at the moment to try to change background color , like this:
Padding(
                padding: const EdgeInsets.all(8.0),
                child: ModalDrawerHandle(
                  handleColor: kColorBackground,
                ),
              ),

The modal drawer does not change the color of background , it still has the default color,, which  is white.

Could you help me please.

Thank you.

**Comment by GroovinChip** [comment]
Hi @Liliana99,

Thanks for opening this issue. This library has been deprecated and folded into my larger widget library, groovin_widgets. If you wouldn't mind re-filing this issue there I'll be happy to take a look.

Thanks.
